// charter5/react-test/src/containers/TodoList/components/UndoList.js
import React, { Component } from 'react';

class UndoList extends Component {
  render() {
    const { list, deleteItem } = this.props;
    return (
      <div>
        <div data-test="count">{ list.length }</div>
        <ul>
          {
            list.map((item, index) =>
              <li
                data-test="list-item"
                key={ `${item}-${index}` }
              >
                { item }
                <span
                  data-test="delete-item"
                  onClick={ () => { deleteItem(index) } }
                >-</span>
              </li>
            )
          }
        </ul>
      </div>
    );
  }
}

export default UndoList;

// charter4/vue-test/src/containers/TodoList/components/UndoList.vue
<template>
  <div>
    <div data-test="count">{{ list.length }}</div>
    <ul>
      <li
        v-for="(item, index) in list"
        :key="item"
        data-test="item"
      >
        {{ item }}
        <span data-test="delete-btn" @click="handleDelete(index)">-</span>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'UndoList',
  props: ['list'],
  methods: {
    handleDelete (index) {
      this.$emit('delete', index)
    }
  }
}
</script>

<style lang="stylus" scoped>

</style>
